### PR TITLE
Fix tests

### LINKED ISSUE #38: 1.3.3; pytest fail in all tests/server_test.py units
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using `installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

python 3.9 and pytest 8.1.0

Please let me know if you need more details or want me to perform some diagnostics.

### PR DESCRIPTION
**Pull request by carlsmedstad**
Hey :wave: Arch Linux maintainer here

This ensures the tests pass on Arch Linux, with the following Python and pytest versions:

```sh
$ python --version
Python 3.12
$ pytest --version
pytest 8.3.2
```

See commit messages for details.

Resolves #38

### CODE REVIEW

**Comment by danvk** [comment]
The tests pass both before & after this PR for me, so I'll go ahead and merge.

```
$ python --version
Python 3.11.9
$ pytest --version
pytest 7.2.2
```

**Comment by carlsmedstad** [comment]
Much appreciated, thank you! Are you planning to release a new version anytime soon? That would relieve me from having to patch our package.

**Comment by danvk** [comment]
Do you want to become an owner of this package?

**Comment by carlsmedstad** [comment]
I would not have anything against maintaining it upstream while it is in our repositories, sure. I don't think I would have time or interest to do any major development, however.

**Comment by danvk** [comment]
Great. I've invited you to collaborate on both this repo and the pypi project. If you're interested, I think conversion to Poetry (#36) would be a nice addition to get in.

**Comment by carlsmedstad** [comment]
Super, good suggestion. I'll start with tagging & publishing 1.3.4 from the current master and go from there, if you don't object :)

**Comment by danvk** [comment]
Sounds good!

**Pull request merged**
