### PR TITLE
Make the code compatible with Python 3

### PR DESCRIPTION
**Pull request by bochecha**
Just a trivial pull request to have this module run with Python 3.

Note that the `io` module was introduced in Python 2.6, so if you want to remain compatible with older versions then this pull request needs a tiny little bit more work. :smiley:

### CODE REVIEW

**Comment by bochecha** [comment]
First commit broke Python 2... sorry about that.

This is now fixed, the tests run with both Python 2 and 3.

**Comment by bochecha** [comment]
I just realize you used to be compatible with Python 3, then you [reverted the commit](https://github.com/danvk/RangeHTTPServer/commit/abe6245751b10404b71dab0bb5542b5e59cad55b).

Why? Was that causing trouble?

**Comment by danvk** [comment]
I reverted because it no longer worked with Python 2. Can you update `.travis.yml` to run the tests in both 2 & 3?

**Comment by bochecha** [comment]
> Can you update .travis.yml to run the tests in both 2 & 3?

Sure, done. :smile: 

I didn't know which versions of Python 3 you wanted to support, so I did both 3.4 and 3.5. Python 3.5 is the latest and greatest; and 3.4 is what is in most distros today, so I figured they were both interesting.

**Comment by danvk** [comment]
Thanks!

**Pull request merged**
