### PR TITLE
Make a package

### LINKED ISSUE #9: Warnings when installing via pip
I'm getting `WARNING: '.' not a valid package name` when installing via `pip install RangeHTTPServer`. Maybe I need to move `RangeHTTPServer.py` into a `rangehttpserver` package.

```
pip install RangeHTTPServer
Downloading/unpacking RangeHTTPServer
  Downloading rangehttpserver-1.1.1.tar.gz
  Running setup.py (path:/private/var/folders/9q/340_463n2fvbzjg232s3hrt00000gn/T/pip_build_danvk/RangeHTTPServer/setup.py) egg_info for package RangeHTTPServer
    WARNING: '.' not a valid package name; please use only.-separated package names in setup.py

    package init file '__init__.py' not found (or not a regular file)
Installing collected packages: RangeHTTPServer
  Running setup.py install for RangeHTTPServer
    WARNING: '.' not a valid package name; please use only.-separated package names in setup.py
    package init file '__init__.py' not found (or not a regular file)

Successfully installed RangeHTTPServer
Cleaning up...
```

### PR DESCRIPTION
**Pull request by bochecha**
Fixes #9

### CODE REVIEW

**Comment by danvk** [comment]
This seems fine to me. @bochecha @berdario are either of you interested in becoming the owner of this package/repo? I don't use it anymore (I've had no reason to since I discovered npm's http-server, which supports range requests out of the box.)

**Comment by bochecha** [comment]
@danvk My only interest in this package is that it ends up in the dependency chain of pew (for unit tests), and I'm trying to package pew in Fedora.

So no, I don't really have an interest in becoming the maintainer of this repo, and I'd do a lousy job anyway. :smile:

**Comment by berdario** [comment]
## It's ok for me

Sent from mobile. Please excuse my brevity.

**Comment by danvk** [comment]
I added you both as collaborators to the repo. If you'd like to become a collaborator on pypi as well, please pass along your pypi.python.org user name.

**Comment by berdario** [comment]
Thank you, sorry for the late reply

My username on pypi is `berdario` as well

**Comment by danvk** [comment]
I made you an owner @berdario. Feel free to cut a release whenever you like.

**Pull request merged**
